stages:
  - test
  - build
  - deploy
  - trigger_pipeline  # Добавил новый этап для триггера

variables:
  DJANGO_SETTINGS_MODULE: "final_project.settings"
  PYTHONPATH: "$CI_PROJECT_DIR"
  DOCKER_IMAGE: "meow-web"
  DOCKER_REGISTRY: "registry.gitlab.com"
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - python -V
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - python manage.py test

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build

deploy:
  stage: deploy
  only:
    - main
  script:
    - docker-compose -f docker-compose.yml up -d
    - docker-compose -f docker-compose.yml exec web python manage.py migrate
    - docker-compose -f docker-compose.yml exec web python manage.py collectstatic --noinput
    - docker-compose -f docker-compose.yml restart web
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag meow-web:latest $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME

trigger_pipeline:
  stage: trigger_pipeline
  script:
    - "curl -X POST --fail -F token=glptt-c04d4bddaa612f2dfd415138bf87253722ae6137 -F ref=debvops https://gitlab.informatics.ru/api/v4/projects/10015/trigger/pipeline"
