stages:
  - test

image: python:3.11

cache:
  paths:
    - .cache/pip

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DJANGO_SETTINGS_MODULE: final_project.settings

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py makemigrations 
    - python manage.py test
  only:
    - merge_requests
    - main
    - master
