# Generated by Django 5.2 on 2025-04-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hats', 'Головные уборы'), ('outerwear', 'Верхняя одежда'), ('tops', 'Топы'), ('bottoms', 'Низы'), ('shoes', 'Обувь')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('image_name', models.CharField(max_length=100)),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
            ],
        ),
    ]
