# Generated by Django 5.2 on 2025-04-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='material',
            field=models.CharField(choices=[('cotton', 'cotton'), ('polyester', 'polyester'), ('flax', 'flax')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
