# Generated by Django 5.2 on 2025-04-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Looks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_grade', models.IntegerField()),
                ('description', models.CharField(max_length=2058)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_project_app.item')),
            ],
        ),
    ]
