# Generated by Django 5.2 on 2025-04-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0002_alter_clothingitem_material_delete_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='material',
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='style',
            field=models.TextField(choices=[('classic', 'classic'), ('casual', 'casual'), ('sport', 'sport'), ('punk', 'punk'), ('military', 'military'), ('emo', 'emo'), ('flex', 'flex')], default='flex'),
        ),
        migrations.AlterField(
            model_name='looks',
            name='style',
            field=models.CharField(choices=[('classic', 'classic'), ('casual', 'casual'), ('sport', 'sport'), ('punk', 'punk'), ('military', 'military'), ('emo', 'emo'), ('flex', 'flex')], default='flex'),
        ),
    ]
