# Generated by Django 5.2 on 2025-04-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0003_remove_clothingitem_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='material',
            field=models.CharField(choices=[('cotton', 'cotton'), ('polyester', 'polyester'), ('flax', 'flax')], default='cotton', max_length=20),
        ),
    ]
