# Generated by Django 5.2 on 2025-04-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0005_alter_clothingitem_material_alter_clothingitem_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='material',
            field=models.CharField(choices=[('cotton', 'cotton'), ('polyester', 'polyester'), ('wool', 'wool'), ('leather', 'leather'), ('denim', 'denim'), ('flax', 'flax'), ('suede', 'suede')], default='cotton', max_length=20),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='style',
            field=models.TextField(choices=[('classic', 'classic'), ('casual', 'casual'), ('sport', 'sport'), ('business', 'business'), ('streetwear', 'streetwear'), ('retro', 'retro'), ('punk', 'punk'), ('military', 'military'), ('grunge', 'grunge'), ('minimalism', 'minimalism')], default='classic'),
        ),
        migrations.AlterField(
            model_name='looks',
            name='style',
            field=models.CharField(choices=[('classic', 'classic'), ('casual', 'casual'), ('sport', 'sport'), ('business', 'business'), ('streetwear', 'streetwear'), ('retro', 'retro'), ('punk', 'punk'), ('military', 'military'), ('grunge', 'grunge'), ('minimalism', 'minimalism')], default='classic'),
        ),
    ]
