# Generated by Django 5.2 on 2025-04-19 16:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0005_alter_clothingitem_material_alter_clothingitem_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='looks',
            name='bottom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottom_looks', to='final_project_app.clothingitem'),
        ),
        migrations.AddField(
            model_name='looks',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='looks',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_looks', to='final_project_app.clothingitem'),
        ),
        migrations.AddField(
            model_name='looks',
            name='max_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='looks',
            name='min_temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='looks',
            name='outerwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outerwear_looks', to='final_project_app.clothingitem'),
        ),
        migrations.AddField(
            model_name='looks',
            name='shoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoes_looks', to='final_project_app.clothingitem'),
        ),
        migrations.AddField(
            model_name='looks',
            name='top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_looks', to='final_project_app.clothingitem'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='material',
            field=models.CharField(choices=[('cotton', 'cotton'), ('polyester', 'polyester'), ('wool', 'wool'), ('leather', 'leather'), ('denim', 'denim'), ('flax', 'flax'), ('suede', 'suede')], default='cotton', max_length=20),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='style',
            field=models.TextField(choices=[('classic', 'classic'), ('casual', 'casual'), ('sport', 'sport'), ('business', 'business'), ('streetwear', 'streetwear'), ('retro', 'retro'), ('punk', 'punk'), ('military', 'military'), ('grunge', 'grunge'), ('minimalism', 'minimalism')], default='classic'),
        ),
        migrations.AlterField(
            model_name='looks',
            name='style',
            field=models.CharField(choices=[('classic', 'classic'), ('casual', 'casual'), ('sport', 'sport'), ('business', 'business'), ('streetwear', 'streetwear'), ('retro', 'retro'), ('punk', 'punk'), ('military', 'military'), ('grunge', 'grunge'), ('minimalism', 'minimalism')], default='classic'),
        ),
    ]
