# Generated by Django 5.2 on 2025-04-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0006_looks_bottom_looks_created_at_looks_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='looks',
            name='items',
        ),
    ]
