# Generated by Django 5.2 on 2025-04-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0006_alter_clothingitem_material_alter_clothingitem_style_and_more'),
        ('final_project_app', '0007_remove_looks_items'),
    ]

    operations = [
    ]
