# Generated by Django 5.2 on 2025-04-22 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0008_merge_20250421_2118'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='looks',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_looks', to=settings.AUTH_USER_MODEL),
        ),
    ]
