# Generated by Django 5.2 on 2025-04-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0010_dislikedlook_likedlook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='looks',
            name='description',
        ),
        migrations.RemoveField(
            model_name='looks',
            name='max_temp',
        ),
        migrations.RemoveField(
            model_name='looks',
            name='min_temp',
        ),
        migrations.RemoveField(
            model_name='looks',
            name='style',
        ),
        migrations.RemoveField(
            model_name='looks',
            name='weather_grade',
        ),
        migrations.AddField(
            model_name='looks',
            name='bottom_color',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='bottom_image',
            field=models.CharField(default='default.png', max_length=255),
        ),
        migrations.AddField(
            model_name='looks',
            name='bottom_material',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='bottom_style',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='head_color',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='head_image',
            field=models.CharField(default='default.png', max_length=255),
        ),
        migrations.AddField(
            model_name='looks',
            name='head_material',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='head_style',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='outerwear_color',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='outerwear_image',
            field=models.CharField(default='default.png', max_length=255),
        ),
        migrations.AddField(
            model_name='looks',
            name='outerwear_material',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='outerwear_style',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='shoes_color',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='shoes_image',
            field=models.CharField(default='default.png', max_length=255),
        ),
        migrations.AddField(
            model_name='looks',
            name='shoes_material',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='shoes_style',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='temp_range',
            field=models.CharField(default='unknown_range', max_length=20),
        ),
        migrations.AddField(
            model_name='looks',
            name='top_color',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='top_image',
            field=models.CharField(default='default.png', max_length=255),
        ),
        migrations.AddField(
            model_name='looks',
            name='top_material',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='looks',
            name='top_style',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='looks',
            name='bottom',
            field=models.CharField(default='no_bottom', max_length=255),
        ),
        migrations.AlterField(
            model_name='looks',
            name='head',
            field=models.CharField(default='no_head', max_length=255),
        ),
        migrations.AlterField(
            model_name='looks',
            name='outerwear',
            field=models.CharField(default='no_outerwear', max_length=255),
        ),
        migrations.AlterField(
            model_name='looks',
            name='shoes',
            field=models.CharField(default='no_shoes', max_length=255),
        ),
        migrations.AlterField(
            model_name='looks',
            name='top',
            field=models.CharField(default='no_top', max_length=255),
        ),
    ]
