# Generated by Django 5.2 on 2025-04-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0011_remove_looks_description_remove_looks_max_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='looks',
            name='bottom_vector',
            field=models.CharField(default='no_vector', max_length=255),
        ),
        migrations.AddField(
            model_name='looks',
            name='general_vector',
            field=models.CharField(default='no_general_vector', max_length=1024),
        ),
        migrations.AddField(
            model_name='looks',
            name='head_vector',
            field=models.CharField(default='no_vector', max_length=255),
        ),
        migrations.AddField(
            model_name='looks',
            name='outerwear_vector',
            field=models.CharField(default='no_vector', max_length=255),
        ),
        migrations.AddField(
            model_name='looks',
            name='shoes_vector',
            field=models.CharField(default='no_vector', max_length=255),
        ),
        migrations.AddField(
            model_name='looks',
            name='top_vector',
            field=models.CharField(default='no_vector', max_length=255),
        ),
    ]
