# Generated by Django 5.2 on 2025-04-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0012_looks_bottom_vector_looks_general_vector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='looks',
            name='created_at',
        ),
    ]
