# Generated by Django 5.2 on 2025-04-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0013_remove_looks_created_at'),
    ]

    operations = [
    ]
