# Generated by Django 5.2 on 2025-04-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0015_create_looks_table'),
    ]

    operations = [
    ]
