# Generated by Django 5.2 on 2025-05-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0016_create_looks_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='info',
            name='height',
        ),
        migrations.RemoveField(
            model_name='info',
            name='hips',
        ),
        migrations.RemoveField(
            model_name='info',
            name='waist',
        ),
        migrations.RemoveField(
            model_name='info',
            name='weight',
        ),
    ]
