# Generated by Django 5.2 on 2025-05-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0017_remove_info_chest_remove_info_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
