# Generated by Django 5.2 on 2026-08-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0018_alter_likedlook_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='looks',
            name='items',
        ),
        migrations.RemoveField(
            model_name='looks',
            name='weather_grade',
        ),
        migrations.AddField(
            model_name='looks',
            name='bottom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='looks',
            name='bottom_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='bottom_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='looks',
            name='bottom_material',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='bottom_style',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='general_vector',
            field=models.CharField(default='', max_length=2058),
        ),
        migrations.AddField(
            model_name='looks',
            name='head',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='looks',
            name='head_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='head_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='looks',
            name='head_material',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='head_style',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='outerwear',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='looks',
            name='outerwear_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='outerwear_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='looks',
            name='outerwear_material',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='outerwear_style',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='shoes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='looks',
            name='shoes_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='shoes_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='looks',
            name='shoes_material',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='shoes_style',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='temp_range',
            field=models.CharField(default='0_10', max_length=20),
        ),
        migrations.AddField(
            model_name='looks',
            name='top',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='looks',
            name='top_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='top_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='looks',
            name='top_material',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='looks',
            name='top_style',
            field=models.CharField(default='', max_length=50),
        ),
    ]
